app:
  jwt:
    expiration-in-ms: 86400000
    secret: RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!RandomSecretKey1234567890!
spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/flight_booking
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
   
    

flight-api:
  messages:
    FlightSaveSucc: Flight Saved Successfully
    FlightSaveFail: Flight Save Failed
    FlightUpdateSucc: Flight Updated Successfully
    FlightUpdateFail: Flight Update Failed
    FlightDeleteSucc: Flight Deleted Successfully
    FlightDeleteFail: Flight Delete Failed
    FlightStatusChange: Flight Status Changed Successfully
    FlightStatusChangeFail: Flight Status Change Failed
    
    
booking-api:
  messages:
    BookingSaveSucc: Booking Saved Successfully
    BookingSaveFail: Booking Save Failed
    BookingUpdateSucc: Booking Updated Successfully
    BookingUpdateFail: Booking Update Failed
    BookingDeleteSucc: Booking Deleted Successfully
    BookingDeleteFail: Booking Delete Failed
    BookingStatusChange: Booking Status Changed Successfully
    BookingStatusChangeFail: Booking Status Change Failed
    
    
passenger-api:
  messages:
    PassengerSaveSucc: Passenger Saved Successfully
    PassengerSaveFail: Passenger Save Failed
    PassengerUpdateSucc: Passenger Updated Successfully
    PassengerUpdateFail: Passenger Update Failed
    PassengerDeleteSucc: Passenger Deleted Successfully
    PassengerDeleteFail: Passenger Delete Failed
    PassengerStatusChange: Passenger Status Changed Successfully
    PassengerStatusChangeFail: Passenger Status Change Failed